bases:
- https://github.com/bigkevmcd/taxi/deploy/templates
configMapGenerator:
- name: www-files
  files:
  - index.html
  - staging.html
images:
- name: quay.io/kmcdermo/taxi
  newName: quay.io/kmcdermo/hello-kotlin
  newTag: latest
