bases:
- https://github.com/bigkevmcd/taxi/deploy/templates
configMapGenerator:
- name: stage-www-files
  files:
  - index.html
  - staging.html
images:
- name: quay.io/kmcdermo/taxi
  newTag: dd933b8316e67fbb83e1259aeaf3d9a244bbad95
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: taxi
  path: staging_patch.yaml
